### ISSUE TITLE
Stopwatch in time tracker

### ISSUE THREAD

**Issue by shubhamgohad221997** [Durgashankar001/clockify_clone#21]
- [x] Create Stopwatch
- [x] Show time in the hour
- [x] Show time in the minutes
- [x] Show time in the seconds
